config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Users
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  # Sessions
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  root to: 'people#index'

  resources :people do
    resources :phones
    resources :emails
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
  validates :street, presence: true
  validates :town, presence: true
  validates :zip, presence: true

  enum country: { usa: 'USA', can: 'Canada', mex: 'Mexico' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person
  validates :address, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :phones, dependent: :destroy
  has_many :emails, dependent: :destroy
  has_many :addresses, dependent: :destroy

  accepts_nested_attributes_for :emails, allow_destroy: true, reject_if: lambda { |attributes|
                                                                           attributes['address'].blank?
                                                                         }
  accepts_nested_attributes_for :phones, allow_destroy: true, reject_if: lambda { |attributes|
                                                                           attributes['number'].blank?
                                                                         }

  accepts_nested_attributes_for :addresses, allow_destroy: true, reject_if: lambda { |attributes|
                                                                              attributes['street'].blank? && attributes['town'].blank? && attributes['zip'].blank?
                                                                            }

  enum salutation: { mr: 'Mr.', ms: 'Ms.', mrs: 'Mrs.' }

  validates :firstname, :lastname, presence: true
  validates_associated :phones, :emails, :addresses

  def build_nested_attributes
    phones.build if phones.empty?
    emails.build if emails.empty?
    addresses.build if addresses.empty?
  end
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :person
  validates :number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :people, dependent: :destroy
  validates :email, presence: true, uniqueness: true, allow_nil: false
  validates :name, presence: true, allow_nil: false
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate_user!
    redirect_to login_path, alert: 'Please log in' unless current_user
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /people or /people.json
  def index
    @people = current_user.people
    respond_to do |format|
      format.html
      format.json { render json: @people }
    end
  end

  # GET /people/1 or /people/1.json
  def show
    @person || respond_to do |format|
      format.html { redirect_to people_path, notice: "You don't have access to that Person" }
      format.json { render json: { error: "You don't have access to that Person" }, status: :unauthorized }
    end
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.build_nested_attributes
  end

  # GET /people/1/edit
  def edit
    @person.build_nested_attributes
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: 'Person was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Person was successfully created.' }
        format.json { render :show, status: :created, person: @person }
      else
        @person.build_nested_attributes

        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@person, partial: 'people/form', locals: { person: @person })
        end
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: 'Person was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Person was successfully updated.' }
        format.json { render :show, status: :ok, person: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
      # The page doesn't update automatically... maybe this is where those destroy.turbo_stream.erb files come in?
      format.turbo_stream { flash.now[:notice] = 'Person was successfully deleted.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.where(id: params[:id], user_id: current_user.id).first
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(
      :firstname,
      :middlename,
      :lastname,
      :ssn,
      :birthdate,
      :comment,
      :salutation,
      phones_attributes: %i[id number comment _destroy],
      emails_attributes: %i[id address comment _destroy],
      addresses_attributes: %i[id street town zip state country _destroy]
    )
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
      flash[:success] = "Welcome back, #{@user.name}!"
    else
      redirect_to login_path
      flash[:danger] = 'Invalid email/password combination'
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_path, notice: 'Logged out!'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    @user = User.new(user_params)
    if @user.save
      # This logs the user in after they sign up successfully.
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity, flash: { error: @user.errors.full_messages }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_address.html.erb
<template data-nested-form-target="addressTemplate">
  <%= form.fields_for :addresses, child_index: "NEW_RECORD" do |addresses_form| %>
    <%= render "addresses/address_form", f: addresses_form %>
  <% end %>
</template>

<%= form.fields_for :addresses do |addresses_form| %>
  <%= render "addresses/address_form", f: addresses_form %>
<% end %>

<!-- Inserted elements will be injected before that target. -->
<div data-nested-form-target="address"></div>

<div class="d-flex justify-content-end pt-3 pe-3">
  <button type="button" data-action="nested-form#add" data-field-scope="address" class="btn btn-sm btn-outline-primary">Add Another Address</button>
</div>

app/views/addresses/_address_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="rounded-3 p-3 mb-3 bg-light">
    <div class="row">
      <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
        <%= f.label :street, "Street", class: "form-label" %>
        <%= f.text_field :street, class: "form-control" %>
      </div>
      <div class="col-12  col-sm-6 col-lg-4 col-xl-3">
        <%= f.label :town, "Town", class: "form-label" %>
        <%= f.text_field :town, class: "form-control" %>
      </div>
      <div class="col-12 col-sm-6 col-lg-4 col-xl-2">
        <%= f.label :zip, "Zip code: (#####)", class: "form-label" %>
        <%= f.text_field :zip, class: "form-control" %>
      </div>
      <div class="col-12 col-sm-6 col-lg-4 col-xl-2">
        <%= f.label :state, "State", class: "form-label" %>
        <%= f.text_field :state, class: "form-control" %>
      </div>
      <div class="col-12 col-sm-6 col-lg-4 col-xl-2">
        <%= f.label :country, class: "form-label" %>
        <%= f.collection_select :country, Address.countries, :first, :last, { include_blank: true }, class: "form-select" %>
      </div>
      <%= f.hidden_field :_destroy %>
      <div class="d-flex justify-content-end pt-3">
        <button type="button" data-action="nested-form#remove" class="btn btn-sm btn-outline-danger">Remove address</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message alert alert-info" data-controller="removals" data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid p-0">
    <a class="navbar-brand" href="/">PeopleApp</a>
    <% if current_user %>
      <span class="text-success">Signed in as <%= current_user.name %></span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto align-items-end align-items-lg-center">
        <li class="nav-item">
          <% if current_user %>
            <a class="nav-link" href="/logout">Log out</a>
          <% else %>
            <a class="nav-link" href="/login">Log in</a>
          <% end %>
        </li>
      </li>

    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="bg-light">
      <div class="container">
        <%= render 'layouts/nav' %>
      </div>
    </div>

    <div class="container">
      <div id="flash" class="flash">
        <%= render "layouts/flash" %>
      </div>

      <%= yield %>

    </body>
  </html>

app/views/people/_form.html.erb
<%= form_with model: person, id: dom_id(person), data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper'} do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h3>

      <ul>
        <% person.errors.each do |error| %>
          <li class="text-danger"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="border rounded-3 p-3 mb-3 shadow">
    <h3>Personal info</h3>
    <div class="rounded-3 p-3 mb-3 bg-light">
      <div class="row mb-lg-3">
        <%# Salutation %>
        <div class="mb-2 mb-md-0 col-12 col-md-4 col-lg-2 col-xl-2">
          <%= form.label :salutation, class: "form-label" %>
          <%= form.collection_select :salutation, Person.salutations, :first, :last, { include_blank: true }, class: "form-select" %>
        </div>
        <%# Birthdate and SSN %>
        <div class="mb-2 mb-md-0 col-12 col-md-4 col-lg-4 offset-lg-2">
          <%= form.label :birthdate, class: "form-label" %>
          <%= form.date_field :birthdate, class: "form-control" %>
        </div>
        <div class="mb-2 mb-md-0 col-12 col-md-4 col-lg-4">
          <%= form.label :ssn, "SSN: (#########)", class: "form-label" %>
          <%= form.text_field :ssn, class: "form-control" %>
        </div>
      </div>
      <%# Name Inputs %>
      <div class="row">
        <div class="mb-2 mb-md-0 col-12 col-md-4">
          <%= form.label :firstname, "Firstname (required)", class: "form-label" %>
          <%= form.text_field :firstname, class: "form-control" %>
          <div class="invalid-feedback">
            Please provide a Firstname.
          </div>
          <div class="valid-feedback">Looks good!</div>
        </div>
        <div class="mb-2 mb-md-0 col-12 col-md-4">
          <%= form.label :middlename, class: "form-label" %>
          <%= form.text_field :middlename, class: "form-control" %>
        </div>
        <div class="mb-2 mb-md-0 col-12 col-md-4">
          <%= form.label :lastname, "Lastname (required)", class: "form-label" %>
          <%= form.text_field :lastname, class: "form-control" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <%# Email Inputs %>
    <div class="col-12 col-md-6">
      <%= render partial: 'emails/email', locals: { form: form }%>
    </div>
    <%# Phone Inputs %>
    <div class="col-12 col-md-6">
      <%= render partial: 'phones/phone', locals: { form: form }%>
    </div>
  </div>
  <%# Address Inputs %>
  <div class="mb-2 p-3 border shadow rounded">
    <h3>Address info</h3>
    <%= render partial: 'addresses/address', locals: { form: form } %>
  </div>
  <%# Comments %>
  <div class="mb-2 p-3 border shadow rounded">
    <%= form.label :comment, class: "form-label" %>
    <%= form.text_area :comment, class: "form-control" %>
  </div>
  <%# SUBMIT %>
  <div class="my-4">
    <%= button_tag "Submit", type: 'submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/people/_person.html.erb
<%= turbo_frame_tag person do %>
  <div class="d-flex align-items-start align-items-sm-center flex-column flex-sm-row border rounded-3 p-3 mb-3 shadow">
    <div class="mb-1 w-100">
      <p class="mb-0">
        <%= person.firstname %>
        <%= person.lastname %>
      </p>
    </div>
    <div class="d-flex mt-2 mt-sm-0 justify-content-start justify-content-sm-end align-items-start flex-shrink-1">
      <%= link_to 'Show', person_path(person), class: 'btn btn-sm btn-outline-primary me-3' %>
      <%= link_to "Edit", edit_person_path(person), class: 'btn btn-sm btn-outline-warning me-3' %>
      <%= link_to "Delete", person_path(person), class: 'btn btn-sm btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
<% end %>

app/views/people/create.turbo_stream.erb
<%= turbo_stream.prepend "people", @person %>
<%= turbo_stream.update Person.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/people/destroy.turbo_stream.erb
<%= turbo_stream.remove @person %>

app/views/people/edit.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Edit Person</h1>
  <%= link_to 'Back', people_path, class: 'btn btn-outline-primary' %>
</div>

<%= turbo_frame_tag @person do %>
  <div class="border rounded-3 p-3 mb-3 shadow">
    <%= link_to 'Back', people_path, class: 'btn btn-outline-primary mb-3' %>
    <%= render 'form', person: @person %>
  </div>
<% end %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>
<h2>People</h2>
<%= link_to 'Add a Person', new_person_path, class: 'btn btn-primary my-4', data: { turbo_frame: dom_id(Person.new) } %>

<div class="d-flex flex-column justify-content-around">
  <%# <div class="col col-md-9 col-lg-6 col-xl-5"> %>
  <div class="col col-md-12">
    <%= turbo_frame_tag Person.new %>
    <%= turbo_frame_tag "people" do %>
      <%= render @people %>
    <% end %>
  </div>
</div>

app/views/people/new.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>New Person</h1>
  <%= link_to 'Back', people_path, class: 'btn btn-outline-primary' %>
</div>

<%= turbo_frame_tag @person do %>
  <div class="border rounded-3 p-3 mb-3 shadow">
    <%= link_to 'Back', people_path, class: 'btn btn-outline-primary mb-3' %>
    <%= render 'form', person: @person %>
  </div>
<% end %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<%= turbo_frame_tag @person do %>
  <div class="border rounded-3 p-3 mb-3 shadow">
    <div class="mb-4 w-100 d-flex justify-content-between align-items-end">
      <h2 class="text-primary mb-0">
        <%= @person.firstname %>
        <%= @person.middlename %>
        <%= @person.lastname %>
      </h2>
      <div class="d-flex justify-content-start justify-content-sm-end align-items-start flex-shrink-1 gap-2">
        <%= link_to 'Back', people_path, class: 'btn btn-outline-primary' %>
        <%= link_to "Edit", edit_person_path(@person), class: 'btn btn-outline-warning' %>
        <%= link_to "Delete", person_path(@person), class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <div class="d-flex flex-column flex-sm-row gap-3">
      <div class="mb-4 w-100 border border-light bg-light rounded-3 p-3">
        <h3 class="text-secondary">Birthdate</h3>
        <%= @person.birthdate %>
      </div>
      <div class="mb-4 w-100 border border-light bg-light rounded-3 p-3">
        <h3 class="text-secondary">SSN</h3>
        <%= @person.ssn %>
      </div>
    </div>
    <div class="mb-4 w-100 border border-light bg-light rounded-3 p-3">
      <h3 class="text-secondary">Phones:</h3>
      <% @person.phones.each do |phone| %>
        <p><%= phone.number %></p>
        <p><%= phone.comment %></p>
      <% end %>
    </div>
    <div class="mb-4 w-100 border border-light bg-light rounded-3 p-3">
      <h3 class="text-secondary">Emails:</h3>
      <% @person.emails.each do |email| %>
        <p><%= email.address %></p>
        <p><%= email.comment %></p>
      <% end %>
    </div>
    <div class="mb-4 w-100 border border-light bg-light rounded-3 p-3">
      <h3 class="text-secondary">Addresses:</h3>
      <div class="d-flex">
        <% @person.addresses.each do |address| %>
          <p>
            <%= address.street %>
            <%= address.town %>
            <%= address.state %>, 
          </p>
          <p>
            <%= address.zip %>
            <%= Address.countries[address.country] %>
          </p>
        </div>
      <% end %>
    </div>
    <div class="mb-4 100 border border-light bg-light rounded-3 p-3">
      <h3 class="text-secondary">Comments:</h3>
      <p><%= @person.comment %></p>
    </div>
  </div>
<% end %>

app/views/people/update.turbo_stream.erb
<%= turbo_stream.replace @person %>
<%= render_turbo_stream_flash_messages %>

app/views/phones/_phone.html.erb
<div class="border rounded-3 p-3 mb-3 shadow">
  <h3>Phone info</h3>
  <template data-nested-form-target="phoneTemplate">
    <%= form.fields_for :phones, child_index: "NEW_RECORD" do |phones_form| %>
      <%= render "phones/phone_form", f: phones_form %>
    <% end %>
  </template>

  <%= form.fields_for :phones do |phone_form| %>
    <%= render "phones/phone_form", f: phone_form %>
  <% end %>

  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="phone"></div>

  <div class="d-flex justify-content-end pt-3 pe-3">
    <button type="button" data-action="nested-form#add" data-field-scope="phone" class="btn btn-sm btn-outline-primary">Add Another Phone</button>
  </div>

</div>

app/views/phones/_phone_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <div class="mb-2 border border-light bg-light rounded-3 p-3">
    <div class="mb-2">
      <%= f.label :number, "Phone number (##########)", class: "form-label" %>
      <%= f.phone_field :number, class: "form-control" %>
    </div>
    <div class="w-100">
      <%= f.label :comment, "Comment", class: "form-label" %>
      <%= f.text_area :comment, class: "form-control" %>
    </div>
    <%= f.hidden_field :_destroy %>
    <div class="d-flex justify-content-end pt-3">
      <button type="button" data-action="nested-form#remove" class="btn btn-sm btn-outline-danger">Remove phone</button>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="d-flex flex-column align-items-center p-3">
  <h2>Sign Up!</h2>

  <div class="col col-sm-6 col-md-4 col-lg-3">
    <%= form_for :user do |form| %>
      <% if @user && @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%# Form %>
      <div class="mb-3">
        <%= form.label :name, class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= form.label :email, class: 'form-label' %>
        <%= form.email_field :email, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= form.label :password, class: 'form-label' %>
        <%= form.password_field :password, class: 'form-control' %>
      </div>
      <div class="mb-3">
        <%= submit_tag "Sign Up", class: 'btn btn-primary' %>
      </div>
    <% end %>

  </div>
</div>